# See http://doc.gitlab.com/ce/ci/yaml/README.html

# validate:
#   script:
#     - validate v1
#     - pytest -v

      # Deploy application to a server
deploy:
  stage: deploy
  script: deploy
  only: [master]                          # Only deploy on master branch commit
  tags: [py3]
  variables:
    SERVER: ubuntu@uat.gramener.com       # Deploy to uat.gramener.com/app-name/
    URL: modelhandler-demo                         # Change this to your app-name
    SETUP: sh setup.sh   # You can use any setup script here
    VERSION: py3v1                           # v0, v1 or static
    PORT: 8040
