name: scp to gramex.gramener.com
on:
  push:
    branches:
      - 'master'
      - 'jd*'
jobs:
  build:
    runs-on: [ubuntu-latest]
    name: copy
    steps:
    - uses: actions/checkout@master
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: gramex.gramener.com
        username: ubuntu
        source: "*"
        target: "/home/ubuntu/apps/"
